name: Publish to GH Pages
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.150.1/hugo_0.150.1_linux-amd64.tar.gz'
          tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo          

      - name: Build
        run: ${RUNNER_TEMP}/hugo --minify --cleanDestinationDir

      - name: Create .nojekyll file
        run: touch public/.nojekyll

      - name: Deploy to gh-pages
        run: |
          git init
          git checkout --orphan gh-pages
          git reset --hard
          cp -R public/* .
          git add .
          git config user.name 'rohnson1999'
          git config user.email 'hrs.199921@gmail.com'
          git commit -m 'Deploy to gh-pages'
          git push --force origin gh-pages